# Generated by Django 4.1 on 2024-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ied', models.DateTimeField()),
                ('maturity', models.DateTimeField()),
                ('cycle_of_rent_payment', models.CharField(max_length=10)),
                ('rent_pay_date', models.DateTimeField(blank=True, null=True)),
                ('rent', models.FloatField()),
                ('fee_rate', models.FloatField(blank=True, null=True)),
                ('fee_payment_date', models.DateTimeField(blank=True, null=True)),
                ('cycle_of_fee_payment', models.CharField(blank=True, max_length=10, null=True)),
                ('rent_scaling_rate', models.FloatField(blank=True, null=True)),
                ('rent_scaling_date', models.DateTimeField(blank=True, null=True)),
                ('cycle_of_rent_scaling', models.CharField(blank=True, max_length=10, null=True)),
                ('penalty_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
