# Generated by Django 4.1 on 2024-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='fee_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='penalty_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='rent_scaling_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
