# Generated by Django 4.1 on 2024-08-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_financialdata_fee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='contract_identifier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='contract_type',
            field=models.CharField(default='Lease', max_length=20),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='late_payment_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='fee_payment_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='ied',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='maturity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='rent_pay_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='rent_scaling_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
