# Generated by Django 4.1 on 2024-08-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_financialdata_contract_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='maintenance_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='maintenance_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
